spring.application.name=cursos-virtuales-backend
server.port=8080

# ===== SQL Server =====
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=cursos_virtuales_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=briandb

# ===== JPA =====
# none: las tablas las creó nuestro script SQL
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===== Muestra en consola los endpoints registrados al arrancar =====
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE