spring.application.name=cursos

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=cursos_virtuales;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=briandb

# "none": las tablas ya las creamos con el script SQL, Hibernate no las toca
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Cerramos la conexión al terminar el service (buena práctica)
spring.jpa.open-in-view=false